package com.ar.facturacion.model;
// Generated 02/02/2020 19:45:42 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name="categoria",catalog="tesis")
public class Categoria  implements Serializable {
     private Integer codCategoria;
     private String nomCategoria;
     private String descripcion;
     private Date lastUpdate;
     private int userUpdate;
     private List<Producto> productos = new ArrayList<Producto>();

    public Categoria() {
    }

	
    public Categoria(Integer codCategoria, String nomCategoria, String descripcion, Date lastUpdate, int userUpdate) {
        this.codCategoria = codCategoria;
        this.nomCategoria = nomCategoria;
        this.descripcion = descripcion;
        this.lastUpdate = lastUpdate;
        this.userUpdate = userUpdate;
        
    }
    public Categoria(Integer codCategoria, String nomCategoria, String descripcion, Date lastUpdate, int userUpdate, List<Producto> productos) {
       this.codCategoria = codCategoria;
       this.nomCategoria = nomCategoria;
       this.descripcion = descripcion;
       this.lastUpdate = lastUpdate;
       this.userUpdate = userUpdate;
       this.productos = productos;
    }
   
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="codCategoria", unique=true)
    public Integer getCodCategoria() {
        return this.codCategoria;
    }
    
    public void setCodCategoria(Integer codCategoria) {
        this.codCategoria = codCategoria;
    }

    
    @Column(name="nomCategoria", nullable=false, length=50)
    public String getNomCategoria() {
        return this.nomCategoria;
    }
    
    public void setNomCategoria(String nomCategoria) {
        this.nomCategoria = nomCategoria;
    }

    
    @Column(name="descripcion", nullable=false, length=65535)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastUpdate", length=19)
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    
    @Column(name="userUpdate", nullable=false)
    public int getUserUpdate() {
        return this.userUpdate;
    }
    
    public void setUserUpdate(int userUpdate) {
        this.userUpdate = userUpdate;
    }


@OneToMany(fetch=FetchType.LAZY, mappedBy="categoria", cascade = CascadeType.ALL)
//@org.hibernate.annotations.Cascade(org.hibernate.annotations.CascadeType.ALL)
  
    public List<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(List<Producto> productos) {
        this.productos = productos;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 97 * hash + Objects.hashCode(this.codCategoria);
        hash = 97 * hash + Objects.hashCode(this.nomCategoria);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Categoria other = (Categoria) obj;
        if (!Objects.equals(this.nomCategoria, other.nomCategoria)) {
            return false;
        }
        if (!Objects.equals(this.codCategoria, other.codCategoria)) {
            return false;
        }
        return true;
    }




}


