package com.ar.facturacion.model;
// Generated 02/02/2020 19:45:42 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detalle generated by hbm2java
 */
@Entity
@Table(name="detalle",catalog="tesis")
public class Detalle  implements java.io.Serializable {
     private DetalleId id;
     private Cbtesasoc cbtesasoc;
     private Producto producto;
     private int cantidad;

    public Detalle() {
    }

    public Detalle(DetalleId id, Cbtesasoc cbtesasoc, Producto producto, int cantidad) {
       this.id = id;
       this.cbtesasoc = cbtesasoc;
       this.producto = producto;
       this.cantidad = cantidad;
    }
   
    @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="codComprobante", column=@Column(name="codComprobante", nullable=false) ), 
        @AttributeOverride(name="codproducto", column=@Column(name="codproducto", nullable=false) ) } )
    public DetalleId getId() {
        return this.id;
    }
    
    public void setId(DetalleId id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codComprobante", nullable=false, insertable=false, updatable=false)
    public Cbtesasoc getCbtesasoc() {
        return this.cbtesasoc;
    }
    
    public void setCbtesasoc(Cbtesasoc cbtesasoc) {
        this.cbtesasoc = cbtesasoc;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codproducto", nullable=false, insertable=false, updatable=false)
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    
    @Column(name="Cantidad", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


