package com.ar.facturacion.model;
// Generated 02/02/2020 19:45:42 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DetalleId generated by hbm2java
 */
@Embeddable
public class DetalleId  implements java.io.Serializable {
     private int codComprobante;
     private int codproducto;

    public DetalleId() {
    }

    public DetalleId(int codComprobante, int codproducto) {
       this.codComprobante = codComprobante;
       this.codproducto = codproducto;
    }
    @Column(name="codComprobante", nullable=false)
    public int getCodComprobante() {
        return this.codComprobante;
    }
    
    public void setCodComprobante(int codComprobante) {
        this.codComprobante = codComprobante;
    }


    @Column(name="codproducto", nullable=false)
    public int getCodproducto() {
        return this.codproducto;
    }
    
    public void setCodproducto(int codproducto) {
        this.codproducto = codproducto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetalleId) ) return false;
		 DetalleId castOther = ( DetalleId ) other; 
         
		 return (this.getCodComprobante()==castOther.getCodComprobante())
 && (this.getCodproducto()==castOther.getCodproducto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodComprobante();
         result = 37 * result + this.getCodproducto();
         return result;
   }   


}


