package com.ar.facturacion.model;
// Generated 02/02/2020 19:45:42 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Doctipo generated by hbm2java
 */
@Entity
@Table(name="doctipo",catalog="tesis")
public class Doctipo  implements java.io.Serializable {
     private int idDoc;
     private String descripcion;
     private String fchDesde;
     private String fchHasta;
     private List<Comprador> compradores = new ArrayList<Comprador>();

    public Doctipo() {
    }

	
    public Doctipo(int idDoc, String descripcion, String fchDesde, String fchHasta) {
        this.idDoc = idDoc;
        this.descripcion = descripcion;
        this.fchDesde = fchDesde;
        this.fchHasta = fchHasta;
    }
    public Doctipo(int idDoc, String descripcion, String fchDesde, String fchHasta, List<Comprador> compradores) {
       this.idDoc = idDoc;
       this.descripcion = descripcion;
       this.fchDesde = fchDesde;
       this.fchHasta = fchHasta;
       this.compradores = compradores;
    }
   
    @Id 
    @Column(name="idDoc", unique=true, nullable=false)
    public int getIdDoc() {
        return this.idDoc;
    }
    
    public void setIdDoc(int idDoc) {
        this.idDoc = idDoc;
    }

    
    @Column(name="descripcion", nullable=false, length=250)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="fchDesde", nullable=false, length=8)
    public String getFchDesde() {
        return this.fchDesde;
    }
    
    public void setFchDesde(String fchDesde) {
        this.fchDesde = fchDesde;
    }

    
    @Column(name="fchHasta", nullable=false, length=8)
    public String getFchHasta() {
        return this.fchHasta;
    }
    
    public void setFchHasta(String fchHasta) {
        this.fchHasta = fchHasta;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="doctipo")
    public List<Comprador> getCompradores() {
        return this.compradores;
    }
    
    public void setCompradores(List<Comprador> compradores) {
        this.compradores = compradores;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 59 * hash + this.idDoc;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Doctipo other = (Doctipo) obj;
        if (this.idDoc != other.idDoc) {
            return false;
        }
        return true;
    }




}


