package com.ar.facturacion.model;
// Generated 02/02/2020 19:45:42 by Hibernate Tools 4.3.1


import java.util.ArrayList;

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Fecaereq generated by hbm2java
 */
@Entity
@Table(name="fecaereq",catalog="tesis")
public class Fecaereq  implements java.io.Serializable {
     private int idFeCaereq;
     private int cantRegistros;
     private Ctetipo cteTipo;
     private Ptoventa ptoVenta;
     private Concepto concepto;
     private Doctipo docTipo;
     private int docNro;
     private int cteDesde;
     private int cteHasta;
     private String cbteFch;
     private double impTotal;
     private double impTotConc;
     private double impNeto;
     private double impOpEx;
     private double impIva;
     private double impTrib;
     private String fchServDesde;
     private String fchServHasta;
     private String fchVtoPago;
     private Tipomoneda monId;
     private double monCotizacion;
     private List<Cbtesasoc> cbtesasocs = new ArrayList<Cbtesasoc>();

    public Fecaereq() {
    }
    public Fecaereq(int idFeCaereq, int cantRegistros, Ctetipo cteTipo, Ptoventa ptoVenta, Concepto concepto, Doctipo docTipo, int docNro, int cteDesde, int cteHasta, String cbteFch, double impTotal, double impTotConc, double impNeto, double impOpEx, double impIva, double impTrib, String fchVtoPago, Tipomoneda monId, double monCotizacion) {
        this.idFeCaereq = idFeCaereq;
        this.cantRegistros = cantRegistros;
        this.cteTipo = cteTipo;
        this.ptoVenta = ptoVenta;
        this.concepto = concepto;
        this.docTipo = docTipo;
        this.docNro = docNro;
        this.cteDesde = cteDesde;
        this.cteHasta = cteHasta;
        this.cbteFch = cbteFch;
        this.impTotal = impTotal;
        this.impTotConc = impTotConc;
        this.impNeto = impNeto;
        this.impOpEx = impOpEx;
        this.impIva = impIva;
        this.impTrib = impTrib;
        this.fchVtoPago = fchVtoPago;
        this.monId = monId;
        this.monCotizacion = monCotizacion;
    }
    public Fecaereq(int idFeCaereq, int cantRegistros, Ctetipo cteTipo, Ptoventa ptoVenta, Concepto concepto, Doctipo docTipo, int docNro, int cteDesde, int cteHasta, String cbteFch, double impTotal, double impTotConc, double impNeto, double impOpEx, double impIva, double impTrib, String fchServDesde, String fchServHasta, String fchVtoPago, Tipomoneda monId, double monCotizacion, List<Cbtesasoc> cbtesasocs) {
       this.idFeCaereq = idFeCaereq;
       this.cantRegistros = cantRegistros;
       this.cteTipo = cteTipo;
       this.ptoVenta = ptoVenta;
       this.concepto = concepto;
       this.docTipo = docTipo;
       this.docNro = docNro;
       this.cteDesde = cteDesde;
       this.cteHasta = cteHasta;
       this.cbteFch = cbteFch;
       this.impTotal = impTotal;
       this.impTotConc = impTotConc;
       this.impNeto = impNeto;
       this.impOpEx = impOpEx;
       this.impIva = impIva;
       this.impTrib = impTrib;
       this.fchServDesde = fchServDesde;
       this.fchServHasta = fchServHasta;
       this.fchVtoPago = fchVtoPago;
       this.monId = monId;
       this.monCotizacion = monCotizacion;
       this.cbtesasocs = cbtesasocs;
    }
   
    @Id 
    @Column(name="idFeCAEReq", unique=true, nullable=false)
    public int getIdFeCaereq() {
        return this.idFeCaereq;
    }
    
    public void setIdFeCaereq(int idFeCaereq) {
        this.idFeCaereq = idFeCaereq;
    }

    
    @Column(name="cantRegistros", nullable=false)
    public int getCantRegistros() {
        return this.cantRegistros;
    }
    
    public void setCantRegistros(int cantRegistros) {
        this.cantRegistros = cantRegistros;
    }

    
    @Column(name="cteTipo", nullable=false)
    public Ctetipo getCteTipo() {
        return this.cteTipo;
    }
    
    public void setCteTipo(Ctetipo cteTipo) {
        this.cteTipo = cteTipo;
    }

    
    @Column(name="ptoVenta", nullable=false)
    public Ptoventa getPtoVenta() {
        return this.ptoVenta;
    }
    
    public void setPtoVenta(Ptoventa ptoVenta) {
        this.ptoVenta = ptoVenta;
    }

    
    @Column(name="concepto", nullable=false)
    public Concepto getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(Concepto concepto) {
        this.concepto = concepto;
    }

    
    @Column(name="DocTipo", nullable=false)
    public Doctipo getDocTipo() {
        return this.docTipo;
    }
    
    public void setDocTipo(Doctipo docTipo) {
        this.docTipo = docTipo;
    }

    
    @Column(name="DocNro", nullable=false)
    public int getDocNro() {
        return this.docNro;
    }
    
    public void setDocNro(int docNro) {
        this.docNro = docNro;
    }

    
    @Column(name="CteDesde", nullable=false)
    public int getCteDesde() {
        return this.cteDesde;
    }
    
    public void setCteDesde(int cteDesde) {
        this.cteDesde = cteDesde;
    }

    
    @Column(name="CteHasta", nullable=false)
    public int getCteHasta() {
        return this.cteHasta;
    }
    
    public void setCteHasta(int cteHasta) {
        this.cteHasta = cteHasta;
    }

    
    @Column(name="CbteFch", nullable=false, length=8)
    public String getCbteFch() {
        return this.cbteFch;
    }
    
    public void setCbteFch(String cbteFch) {
        this.cbteFch = cbteFch;
    }

    
    @Column(name="ImpTotal", nullable=false, precision=13)
    public double getImpTotal() {
        return this.impTotal;
    }
    
    public void setImpTotal(double impTotal) {
        this.impTotal = impTotal;
    }

    
    @Column(name="ImpTotConc", nullable=false, precision=13)
    public double getImpTotConc() {
        return this.impTotConc;
    }
    
    public void setImpTotConc(double impTotConc) {
        this.impTotConc = impTotConc;
    }

    
    @Column(name="ImpNeto", nullable=false, precision=13)
    public double getImpNeto() {
        return this.impNeto;
    }
    
    public void setImpNeto(double impNeto) {
        this.impNeto = impNeto;
    }

    
    @Column(name="ImpOpEx", nullable=false, precision=13)
    public double getImpOpEx() {
        return this.impOpEx;
    }
    
    public void setImpOpEx(double impOpEx) {
        this.impOpEx = impOpEx;
    }

    
    @Column(name="ImpIVA", nullable=false, precision=13)
    public double getImpIva() {
        return this.impIva;
    }
    
    public void setImpIva(double impIva) {
        this.impIva = impIva;
    }

    
    @Column(name="ImpTrib", nullable=false, precision=13)
    public double getImpTrib() {
        return this.impTrib;
    }
    
    public void setImpTrib(double impTrib) {
        this.impTrib = impTrib;
    }

    
    @Column(name="FchServDesde", length=8)
    public String getFchServDesde() {
        return this.fchServDesde;
    }
    
    public void setFchServDesde(String fchServDesde) {
        this.fchServDesde = fchServDesde;
    }

    
    @Column(name="FchServHasta", length=8)
    public String getFchServHasta() {
        return this.fchServHasta;
    }
    
    public void setFchServHasta(String fchServHasta) {
        this.fchServHasta = fchServHasta;
    }

    
    @Column(name="FchVtoPago", nullable=false, length=8)
    public String getFchVtoPago() {
        return this.fchVtoPago;
    }
    
    public void setFchVtoPago(String fchVtoPago) {
        this.fchVtoPago = fchVtoPago;
    }

    
    @Column(name="MonId", nullable=false, length=3)
    public Tipomoneda getMonId() {
        return this.monId;
    }
    
    public void setMonId(Tipomoneda monId) {
        this.monId = monId;
    }

    
    @Column(name="MonCotizacion", nullable=false, precision=6, scale=6)
    public double getMonCotizacion() {
        return this.monCotizacion;
    }
    
    public void setMonCotizacion(double monCotizacion) {
        this.monCotizacion = monCotizacion;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="fecaereq")
    public List<Cbtesasoc> getCbtesasocs() {
        return this.cbtesasocs;
    }
    
    public void setCbtesasocs(List<Cbtesasoc> cbtesasocs) {
        this.cbtesasocs = cbtesasocs;
    }




}


