package com.ar.facturacion.model;
// Generated 02/02/2020 19:45:42 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Modopago generated by hbm2java
 */
@Entity
@Table(name="modopago",catalog="tesis")
public class Modopago  implements java.io.Serializable {
     private int idModoPago;
     private String nombreModoPago;
     private float porcentaje;
     private String descripcion;
     private int userUpdate;
     private String estado;
     private List<Pago> pagos = new ArrayList<Pago>();

    public Modopago() {
    }
    public Modopago(int idModoPago, String nombreModoPago, float porcentaje, String descripcion, int userUpdate, String estado) {
        this.idModoPago = idModoPago;
        this.nombreModoPago = nombreModoPago;
        this.porcentaje = porcentaje;
        this.descripcion = descripcion;
        this.userUpdate = userUpdate;
        this.estado = estado;
    }
    public Modopago(int idModoPago, String nombreModoPago, float porcentaje, String descripcion, int userUpdate, String estado, List<Pago> pagos) {
       this.idModoPago = idModoPago;
       this.nombreModoPago = nombreModoPago;
       this.porcentaje = porcentaje;
       this.descripcion = descripcion;
       this.userUpdate = userUpdate;
       this.estado = estado;
       this.pagos = pagos;
    }
   
    @Id 
    @Column(name="idModoPago", unique=true, nullable=false)
    public int getIdModoPago() {
        return this.idModoPago;
    }
    
    public void setIdModoPago(int idModoPago) {
        this.idModoPago = idModoPago;
    }

    
    @Column(name="nombreModoPago", nullable=false, length=50)
    public String getNombreModoPago() {
        return this.nombreModoPago;
    }
    
    public void setNombreModoPago(String nombreModoPago) {
        this.nombreModoPago = nombreModoPago;
    }

    
    @Column(name="porcentaje", nullable=false, precision=13)
    public float getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(float porcentaje) {
        this.porcentaje = porcentaje;
    }

    
    @Column(name="descripcion", nullable=false, length=65535)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="userUpdate", nullable=false)
    public int getUserUpdate() {
        return this.userUpdate;
    }
    
    public void setUserUpdate(int userUpdate) {
        this.userUpdate = userUpdate;
    }

    
    @Column(name="estado", nullable=false, length=9)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="modopago")
    public List<Pago> getPagos() {
        return this.pagos;
    }
    
    public void setPagos(List<Pago> pagos) {
        this.pagos = pagos;
    }




}


