package com.ar.facturacion.model;
// Generated 02/02/2020 19:45:42 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Permiso generated by hbm2java
 */
@Entity
@Table(name="permiso",catalog="tesis")
public class Permiso  implements Serializable {
     private int idPermiso;
     private Permiso permiso;
     private TipoEnum tipo;
     private String nombre;
     private String url;
     private String icono;
     private List<Rol> rols = new ArrayList<Rol>();
     private List<Permiso> permisos = new ArrayList<Permiso>();

    public Permiso() {
    }
    public enum TipoEnum { 
    submenu, menuitem; 
    }  

	
    public Permiso(int idPermiso, Permiso permiso, TipoEnum tipo, String nombre, String url, String icono) {
        this.idPermiso = idPermiso;
        this.permiso = permiso;
        this.tipo = tipo;
        this.nombre = nombre;
        this.url = url;
        this.icono = icono;
    }
    public Permiso(int idPermiso, Permiso permiso, TipoEnum tipo, String nombre, String url, String icono, List<Rol> rols, List<Permiso> permisos) {
       this.idPermiso = idPermiso;
       this.permiso = permiso;
       this.tipo = tipo;
       this.nombre = nombre;
       this.url = url;
       this.icono = icono;
       this.rols = rols;
       this.permisos = permisos;
    }
   
    @Id 
    @Column(name="idPermiso", unique=true, nullable=false)
    public int getIdPermiso() {
        return this.idPermiso;
    }
    
    public void setIdPermiso(int idPermiso) {
        this.idPermiso = idPermiso;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="permisoPadre", nullable=false)
    public Permiso getPermiso() {
        return this.permiso;
    }
    
    public void setPermiso(Permiso permiso) {
        this.permiso = permiso;
    }

    @Enumerated(EnumType.STRING)
    @Column(name="tipo")
    public TipoEnum getTipo() {
        return this.tipo;
    }
    
    public void setTipo(TipoEnum tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="nombre", nullable=false, length=80)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="url", nullable=false, length=300)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    
    @Column(name="icono", nullable=false, length=50)
    public String getIcono() {
        return this.icono;
    }
    
    public void setIcono(String icono) {
        this.icono = icono;
    }


    @ManyToMany(fetch=FetchType.LAZY, mappedBy="permisos")
    public List<Rol> getRols() {
        return this.rols;
    }
    
    public void setRols(List<Rol> rols) {
        this.rols = rols;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="permiso")
    public List<Permiso> getPermisos() {
        return this.permisos;
    }
    
    public void setPermisos(List<Permiso> permisos) {
        this.permisos = permisos;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + this.idPermiso;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Permiso other = (Permiso) obj;
        if (this.idPermiso != other.idPermiso) {
            return false;
        }
        return true;
    }




}


