package com.ar.facturacion.model;
// Generated 02/02/2020 19:45:42 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ptoventa generated by hbm2java
 */
@Entity
@Table(name="ptoventa",catalog="tesis")
public class Ptoventa  implements java.io.Serializable {
     private int numero;
     private String emisionTipo;
     private String bloqueado;
     private String fchBaja;
     private List<Cbtesasoc> cbtesasocs = new ArrayList<Cbtesasoc>();

    public Ptoventa() {
    }
    public Ptoventa(int numero, String emisionTipo, String bloqueado, String fchBaja) {
        this.numero = numero;
        this.emisionTipo = emisionTipo;
        this.bloqueado = bloqueado;
        this.fchBaja = fchBaja;
    }
    public Ptoventa(int numero, String emisionTipo, String bloqueado, String fchBaja, List<Cbtesasoc> cbtesasocs) {
       this.numero = numero;
       this.emisionTipo = emisionTipo;
       this.bloqueado = bloqueado;
       this.fchBaja = fchBaja;
       this.cbtesasocs = cbtesasocs;
    }
   
    @Id 
    @Column(name="numero", unique=true, nullable=false)
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }

    
    @Column(name="emisionTipo", nullable=false, length=8)
    public String getEmisionTipo() {
        return this.emisionTipo;
    }
    
    public void setEmisionTipo(String emisionTipo) {
        this.emisionTipo = emisionTipo;
    }

    
    @Column(name="bloqueado", nullable=false, length=1)
    public String getBloqueado() {
        return this.bloqueado;
    }
    
    public void setBloqueado(String bloqueado) {
        this.bloqueado = bloqueado;
    }

    
    @Column(name="fchBaja", nullable=false, length=8)
    public String getFchBaja() {
        return this.fchBaja;
    }
    
    public void setFchBaja(String fchBaja) {
        this.fchBaja = fchBaja;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="ptoventa")
    public List<Cbtesasoc> getCbtesasocs() {
        return this.cbtesasocs;
    }
    
    public void setCbtesasocs(List<Cbtesasoc> cbtesasocs) {
        this.cbtesasocs = cbtesasocs;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 47 * hash + this.numero;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Ptoventa other = (Ptoventa) obj;
        if (this.numero != other.numero) {
            return false;
        }
        return true;
    }




}


