package com.ar.facturacion.model;
// Generated 16/02/2020 19:22:30 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Responsabletipo generated by hbm2java
 */
@Entity
@Table(name="responsabletipo",catalog="tesis")
public class Responsabletipo  implements java.io.Serializable {


     private int idResponsable;
     private String descripcion;
     private List<Cbtesasoc> cbtesasocList = new ArrayList<Cbtesasoc>();

    public Responsabletipo() {
    }

	
    public Responsabletipo(int idResponsable, String descripcion) {
        this.idResponsable = idResponsable;
        this.descripcion = descripcion;
    }
    public Responsabletipo(int idResponsable, String descripcion, List<Cbtesasoc> cbtesasocList) {
       this.idResponsable = idResponsable;
       this.descripcion = descripcion;
       this.cbtesasocList = cbtesasocList;
    }
   
    @Id 
    @Column(name="idResponsable", unique=true, nullable=false)
    public int getIdResponsable() {
        return this.idResponsable;
    }
    
    public void setIdResponsable(int idResponsable) {
        this.idResponsable = idResponsable;
    }

    
    @Column(name="descripcion", nullable=false, length=250)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="responsabletipo")
    public List<Cbtesasoc> getCbtesasocs() {
        return this.cbtesasocList;
    }
    
    public void setCbtesasocs(List<Cbtesasoc> cbtesasocs) {
        this.cbtesasocList = cbtesasocs;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 73 * hash + this.idResponsable;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Responsabletipo other = (Responsabletipo) obj;
        if (this.idResponsable != other.idResponsable) {
            return false;
        }
        return true;
    }




}


