package com.ar.facturacion.model;
// Generated 02/02/2020 19:45:42 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tributos generated by hbm2java
 */
@Entity
@Table(name="tributos",catalog="tesis")
public class Tributos  implements java.io.Serializable {
     private Integer idTributo;
     private Tipotributo tipotributo;
     private String descripcion;
     private double baseImp;
     private double alic;
     private double importe;
     private Producto producto;

    public Tributos() {
    }

	
    public Tributos(Tipotributo tipotributo, String descripcion, double baseImp, double alic, double importe) {
        this.tipotributo = tipotributo;
        this.descripcion = descripcion;
        this.baseImp = baseImp;
        this.alic = alic;
        this.importe = importe;
    }
    public Tributos(Tipotributo tipotributo, String descripcion, double baseImp, double alic, double importe, Producto producto) {
       this.tipotributo = tipotributo;
       this.producto = producto;
       this.descripcion = descripcion;
       this.baseImp = baseImp;
       this.alic = alic;
       this.importe = importe;
       this.producto = producto;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="idTributo", unique=true, nullable=false)
    public Integer getIdTributo() {
        return this.idTributo;
    }
    
    public void setIdTributo(Integer idTributo) {
        this.idTributo = idTributo;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipoTributo", nullable=false)
    public Tipotributo getTipotributo() {
        return this.tipotributo;
    }
    
    public void setTipotributo(Tipotributo tipotributo) {
        this.tipotributo = tipotributo;
    }

    
    @Column(name="Descripcion", nullable=false, length=80)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="BaseImp", nullable=false, precision=13)
    public double getBaseImp() {
        return this.baseImp;
    }
    
    public void setBaseImp(double baseImp) {
        this.baseImp = baseImp;
    }

    
    @Column(name="Alic", nullable=false, precision=13)
    public double getAlic() {
        return this.alic;
    }
    
    public void setAlic(double alic) {
        this.alic = alic;
    }

    
    @Column(name="importe", nullable=false, precision=13)
    public double getImporte() {
        return this.importe;
    }
    
    public void setImporte(double importe) {
        this.importe = importe;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idProducto", nullable=false)
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 59 * hash + this.idTributo;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Tributos other = (Tributos) obj;
        if (this.idTributo != other.idTributo) {
            return false;
        }
        return true;
    }




}


